### ISSUE TITLE
Total Count ควรขึ้นว่า Loading ถ้ายังดึงข้อมูลครั้งแรกจาก Server ไม่เสร็จ แทนที่จะขึ้น 0

### ISSUE THREAD

**Issue by Splendith** [narze/popyut#3]
Total Count ควรขึ้นว่า Loading ถ้ายังดึงข้อมูลครั้งแรกจาก Server ไม่เสร็จ แทนที่จะขึ้น 0 เพราะ 
1. User อาจเข้าใจผิดครับว่าข้อมูลหายไปไหน
2. ทำให้ PPS รอบแรกสุดขึ้นเป็นล้านเลย เพราะเป็นผลต่างค่า Total กับ 0

**Comment by narze** [comment]
เท็นด้วยครับ เดี๋ยวจะแก้ไขในคืนนี้นะครับ :pray:

**Comment by narze** [comment]
Fixed in 1c4b0c2
